name: deploy

on:
  pull_request:
    branches: [main]

jobs:
  SSH:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            bash deploy.sh
